[workspace]

members = [
  "emu6502",
  "asm6502",
  "disasm6502",
  "shared6502",
  "ui"
]

[profile.release]
opt-level = 3
lto = true
debug = true
debug-assertions = false

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false
