[workspace]

members = [
  "emu6502"
]

[profile.release]
opt-level = 3
lto = true
debug = true
debug-assertions = false

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false
