[package]
name = "emu6502"
version = "0.1.0"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]
edition = "2018"

[dependencies]
fnv = "1.0.6"

[dev-dependencies]
disasm6502 = { path = "../disasm6502" }
